//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "photo_albums")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub library_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(unique)]
    pub cover_photo_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub album_type: String,
    pub photo_count: i32,
    pub sort_order: i32,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_libraries::Entity",
        from = "Column::LibraryId",
        to = "super::media_libraries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MediaLibraries,
    #[sea_orm(
        belongs_to = "super::photos::Entity",
        from = "Column::CoverPhotoId",
        to = "super::photos::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Photos,
}

impl Related<super::media_libraries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaLibraries.def()
    }
}

impl Related<super::photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Photos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
