//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "photos")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "photos_app_id_source_id_path_key")]
    pub source_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub filename: String,
    #[sea_orm(column_type = "Text", unique_key = "photos_app_id_source_id_path_key")]
    pub path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub width: Option<i32>,
    pub height: Option<i32>,
    pub file_size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mime_type: Option<String>,
    pub taken_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub camera_make: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub camera_model: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lens_model: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub focal_length: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub aperture: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shutter_speed: Option<String>,
    pub iso: Option<i32>,
    pub orientation: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub exif_data: Option<Json>,
    #[sea_orm(column_type = "Double", nullable)]
    pub gps_latitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub gps_longitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub gps_altitude: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub location_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thumbnail_path: Option<String>,
    pub is_favorite: bool,
    pub is_hidden: bool,
    pub photo_album_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub color_dominant: Option<String>,
    pub scanned_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique_key = "photos_app_id_source_id_path_key")]
    pub app_id: Uuid,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::apps::Entity",
        from = "Column::AppId",
        to = "super::apps::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Apps,
    #[sea_orm(
        belongs_to = "super::file_systems::Entity",
        from = "Column::SourceId",
        to = "super::file_systems::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FileSystems,
    #[sea_orm(
        belongs_to = "super::photo_albums::Entity",
        from = "Column::PhotoAlbumId",
        to = "super::photo_albums::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    PhotoAlbums,
}

impl Related<super::apps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Apps.def()
    }
}

impl Related<super::file_systems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileSystems.def()
    }
}

impl Related<super::photo_albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PhotoAlbums.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
