//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "photo_geo_cache")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub lat_key: String,
    #[sea_orm(column_type = "Text")]
    pub lon_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub province: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub city: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub district: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub township: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub adcode: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub country: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
